GtfsCalendarDateRule:
  required:
    - id
    - type
    - hasService
    - appliesOn
    - exceptionType
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: GTFS Calendar Date Rule
  properties:
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    appliesOn:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
      format: date
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    exceptionType:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    hasService:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Relationship
        model: https://schema.org/URL  
      type: array
      description: ''
      items:
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
